# Generated by Django 5.1.3 on 2024-12-03 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=200)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='plantes.plante')),
            ],
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('botaniste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils', to=settings.AUTH_USER_MODEL)),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils', to='plantes.plante')),
            ],
        ),
    ]
